# Generated by Django 4.0.2 on 2022-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_review_owner_alter_project_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(blank=True, choices=[('up', 'Up_vote'), ('down', 'Down_vote')], max_length=200, null=True),
        ),
    ]
